command: [
  "streamlit", 
  "run",
  "pdf_viewer.py"
] 

env:
  - name: "DATABRICKS_VOLUME"
    valueFrom: "volume"
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: "DATABRICKS_SQL_WAREHOUSE"
    valueFrom: "sql_warehouse"